name    'Campadrenalin-mediagoblin'
version '0.0.3'
author 'Campadrenalin'
license 'LGPL'
summary 'Roaming Initiative GMG Configuration'
description 'A fast and consistent way to deploy Mediagoblin to a server.'
project_page 'https://github.com/campadrenalin/roaming-initiative-mediagoblin'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
